from enum import Enum

class RunType(Enum):
    TRAIN = "TRAIN"
    ANALYZE_DIRECTIONS = "ANALYZE_DIRECTIONS"
    ANALYZE_TARGET_DISTRIBUTION = "ANALYZE_TARGET_DISTRIBUTION"
    ANALYZE_SCALE_INVARIANCE = "ANALYZE_SCALE_INVARIANCE"