from enum import Enum

class RunType(Enum):
    TRAIN_SINGLE = "TRAIN_SINGLE"
    TRAIN_MULTIPLE = "TRAIN_MULTIPLE"
    PARSE_DATASET = "PARSE DATASET"
    ANALYZE_DIRECTIONS = "ANALYZE_DIRECTIONS"
    ANALYZE_TARGET_DISTRIBUTION = "ANALYZE_TARGET_DISTRIBUTION"
    ANALYZE_SCALE_INVARIANCE = "ANALYZE_SCALE_INVARIANCE"